/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author sahruli nur rizki
 */
public class FormPPencarianNilaiSiswa extends javax.swing.JPanel {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;
    /**
     * Creates new form FormPPencarianNilaiSiswa
     */
    public FormPPencarianNilaiSiswa() {
        initComponents();
        tbl();
      
    }

 public void tbl(){
     DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
     centerRenderer.setHorizontalAlignment( SwingConstants.CENTER);
        tabelNilaiSiswa.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tabelNilaiSiswa.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tabelNilaiSiswa.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tabelNilaiSiswa.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tabelNilaiSiswa.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tabelNilaiSiswa.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        tabelNilaiSiswa.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        tabelNilaiSiswa.getColumnModel().getColumn(7).setCellRenderer(centerRenderer);
        tabelNilaiSiswa.getColumnModel().getColumn(8).setCellRenderer(centerRenderer);
        tabelNilaiSiswa.getColumnModel().getColumn(9).setCellRenderer(centerRenderer);
        
        tabelNilaiSiswa.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelNilaiSiswa.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelNilaiSiswa.getColumnModel().getColumn(2).setPreferredWidth(15);
        tabelNilaiSiswa.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabelNilaiSiswa.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabelNilaiSiswa.getColumnModel().getColumn(5).setPreferredWidth(25);
        tabelNilaiSiswa.getColumnModel().getColumn(6).setPreferredWidth(25);
        tabelNilaiSiswa.getColumnModel().getColumn(7).setPreferredWidth(25);
        tabelNilaiSiswa.getColumnModel().getColumn(8).setPreferredWidth(25);
        tabelNilaiSiswa.getColumnModel().getColumn(9).setPreferredWidth(25);
       
       
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        formCariNilai = new javax.swing.JTextField();
        tombolCariNilai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNilaiSiswa = new javax.swing.JTable();
        csem = new javax.swing.JComboBox<>();
        formCariNilai1 = new javax.swing.JTextField();
        tombolCariabsen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        formCarijadwal = new javax.swing.JTextField();
        tombolCarijadwal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CARI NILAI, ABSEN, JADWAL PELAJARAN");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIS/NAMA SISWA");

        formCariNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formCariNilaiActionPerformed(evt);
            }
        });

        tombolCariNilai.setBackground(new java.awt.Color(102, 102, 102));
        tombolCariNilai.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tombolCariNilai.setText("CARI DATA NILAI");
        tombolCariNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCariNilaiActionPerformed(evt);
            }
        });

        tabelNilaiSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NISN", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane1.setViewportView(tabelNilaiSiswa);

        csem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEMESTER", "GANJIL", "GENAP" }));

        formCariNilai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formCariNilai1ActionPerformed(evt);
            }
        });

        tombolCariabsen.setBackground(new java.awt.Color(102, 102, 102));
        tombolCariabsen.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tombolCariabsen.setText("CARI DATA ABSEN");
        tombolCariabsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCariabsenActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIS/NAMA SISWA");

        formCarijadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formCarijadwalActionPerformed(evt);
            }
        });

        tombolCarijadwal.setBackground(new java.awt.Color(102, 102, 102));
        tombolCarijadwal.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        tombolCarijadwal.setText("CARI JADWAL MAPEL");
        tombolCarijadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCarijadwalActionPerformed(evt);
            }
        });

        jLabel3.setText("Note : Gunakan titik (10.A/10.B...12.E)");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA KELAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(516, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(csem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(formCariNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombolCariNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(formCariNilai1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tombolCariabsen)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(formCarijadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tombolCarijadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formCariNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolCariNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(csem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formCariNilai1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolCariabsen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formCarijadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolCarijadwal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tombolCariNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCariNilaiActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"NIS","NAMA SISWA","KELAS","MATA PELAJARAN","GURU","SEMESTER","TUGAS","UTS","UAS","HASIL","GRADE"};
       
        tabmode = new DefaultTableModel (null, Baris);
        tabelNilaiSiswa.setModel(tabmode);

        //String sql = "SELECT data_siswa.nisn, data_siswa.nama_siswa,mapel.nama_mapel, kelas.kelas, data_guru.nama_guru,nilai_siswa.nilai_mapel from nilai_siswa INNER JOIN data_siswa on data_siswa.id_siswa = nilai_siswa.id_siswa INNER JOIN kelas ON kelas.id = data_siswa.id_kelas INNER JOIN mapel ON kelas.id = mapel.id_kelas INNER JOIN data_guru ON data_guru.id_guru = mapel.id_guru WHERE data_siswa.nisn  = "+formCariNilai.getText()+"";
        String sql = "select*from t_nilai_siswa where nis like '%"+formCariNilai.getText()+"%' and semester like'%"+csem.getSelectedItem()+"%' or nama_siswa like '%"+formCariNilai.getText()+"%' and semester like'%"+csem.getSelectedItem()+"%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
             
            while(hasil.next()) {
                    
                    
                    String b = hasil.getString("nis");
                    String c = hasil.getString("nama_siswa");
                    
                    String d = hasil.getString("nama_kelas");
                    String e = hasil.getString("nama_mapel");
                    
                    String f = hasil.getString("nama_guru");
                    String g = hasil.getString("semester");
                    String h = hasil.getString("nilai_tugas");
                    String i = hasil.getString("nilai_uts");
                    String j = hasil.getString("nilai_uas");
                    String k = hasil.getString("hasil");
                    String l = hasil.getString("grade");
                
                String[] data = {b,c,d,e,f,g,h,i,j,k,l};
                
               
                { if (sql == null) {
                   JOptionPane.showMessageDialog(null,"Data Tidak Ada");
                    
                } else
                    
                    
                    tabmode.addRow(data);
                    tbl();
                }
                
            }
        } catch (Exception e) {
           
        }
        
        
        
    }//GEN-LAST:event_tombolCariNilaiActionPerformed

    private void formCariNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formCariNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formCariNilaiActionPerformed

    private void formCariNilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formCariNilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formCariNilai1ActionPerformed

    private void tombolCariabsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCariabsenActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"NIS","NAMA","KELAS","HADIR","IZIN","SAKIT","TANPA KETERANGAN","JUMLAH","TANGGAL"};
       
        tabmode = new DefaultTableModel(null, Baris);
        tabelNilaiSiswa.setModel(tabmode);
        String sql = "select k.nis_siswa,s.nama_siswa,s.nama_kelas,k.hadir,k.izin,k.sakit,k.tanpa_keterangan,k.jumlah_kehadiran, DATE_FORMAT(k.tanggal,'%y-%m-%d') AS tgl from t_siswa s INNER JOIN t_absen k on k.nis_siswa=s.NIS where s.NIS like'%"+formCariNilai1.getText()+"%' OR s.nama_siswa like'%"+formCariNilai1.getText()+"%'";
        
        try {
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while (hasil.next()){
                    String a = hasil.getString("nis_siswa");
                    String b = hasil.getString("nama_siswa");
                    String c = hasil.getString("nama_kelas");
                    String d = hasil.getString("hadir");
                    String e = hasil.getString("izin");
                    String f = hasil.getString("sakit");
                    String g = hasil.getString("tanpa_keterangan");
                    String h = hasil.getString("jumlah_kehadiran");
                    
                    String i = hasil.getString("tgl");
                    
                   
                   
                    String[] data={a,b,c,d,e,f,g,h,i};
                    tabmode.addRow(data);
                }
            } catch (Exception e) {
        }
    
        
    }//GEN-LAST:event_tombolCariabsenActionPerformed

    private void formCarijadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formCarijadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formCarijadwalActionPerformed

    private void tombolCarijadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCarijadwalActionPerformed
        // TODO add your handling code here:
         Object[] Baris = {"NAMA MAPEL","NAMA GURU","KELAS","HARI"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelNilaiSiswa.setModel(tabmode);
        String sql = "select * from t_jadwal_mapel where kelas like '%"+formCarijadwal.getText()+"%'";
        
        try {
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while (hasil.next()){
                    String a = hasil.getString("nama_mapel");
                    String b = hasil.getString("nama_guru");
                    String c = hasil.getString("kelas");
                    String d = hasil.getString("hari");
                    
                  
                    
                    String[] data={a,b,c,d};
                    tabmode.addRow(data);
                }
            } catch (Exception e) {
        }
    }//GEN-LAST:event_tombolCarijadwalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> csem;
    private javax.swing.JTextField formCariNilai;
    private javax.swing.JTextField formCariNilai1;
    private javax.swing.JTextField formCarijadwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelNilaiSiswa;
    private javax.swing.JButton tombolCariNilai;
    private javax.swing.JButton tombolCariabsen;
    private javax.swing.JButton tombolCarijadwal;
    // End of variables declaration//GEN-END:variables
}
