/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author sahruli nur rizki
 */
public class FormPSiswa extends javax.swing.JPanel {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;



    String NIS = "";
    String nama_siswa = "";
    String jk = "";
    String nama_kelas = "";
    String id_kelas ="";
    
    /**
     * Creates new form FormPSiswa
     */
    public FormPSiswa() {
        initComponents();
        datatable();
        tampil_combokelas();
        tbl();
        
    }

     protected void aktif() {
        tidsiswa.setEnabled(true);
        tnama.setEnabled(true);
       
        
        tidkelas.setEnabled(true);
        tidsiswa.requestFocus();
    }

    protected void kosong() {
        tidsiswa.setText("");
        tnama.setText("");
      
        
        jk1.setSelected(true);
        tkelas.setSelectedIndex(0);

        tidkelas.setText("");
    }
    
     protected void datatable () {
        
        Object[] Baris = {"NIS","NAMA SISWA","JENIS KELAMIN","KELAS","ID KELAS"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelSiswa.setModel(tabmode);
        String sql = "select * from t_siswa";
        
        try {
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while (hasil.next()){
                    String a = hasil.getString("NIS");
                    String b = hasil.getString("nama_siswa");
                   
                    
                    String c = hasil.getString("jk");
                    String d = hasil.getString("nama_kelas");
                  
                    String e = hasil.getString("id_kelas");

                    String[] data={a,b,c,d,e};
                    tabmode.addRow(data);
                }
            } catch (Exception e) {
        }
    }
  
     
  public void tbl(){
      
     DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
     centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );
      
      
        tabelSiswa.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tabelSiswa.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tabelSiswa.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tabelSiswa.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tabelSiswa.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
      
        
        
        tabelSiswa.getColumnModel().getColumn(0).setPreferredWidth(200);
        tabelSiswa.getColumnModel().getColumn(1).setPreferredWidth(200);
        tabelSiswa.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabelSiswa.getColumnModel().getColumn(3).setPreferredWidth(100);
  }
   
    
    public void tampil_combokelas(){
    
    try{
        
       String sql= "select * From t_kelas ";
        java.sql.Statement stat = conn.createStatement();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        while(rs.next()){
            tkelas.addItem(rs.getString("kelas"));
            
        }
        rs.last();
        int jumlahdata = rs.getRow();
        rs.first();
        
    }catch(Exception e){
        
    }
}
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelSiswa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tidsiswa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jk2 = new javax.swing.JRadioButton();
        jk1 = new javax.swing.JRadioButton();
        tkelas = new javax.swing.JComboBox<>();
        tidkelas = new javax.swing.JTextField();
        tombolSimpan = new javax.swing.JButton();
        tubah = new javax.swing.JButton();
        excel = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        tabl1 = new javax.swing.JButton();
        ctbl = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(984, 547));

        tabelSiswa.setAutoCreateRowSorter(true);
        tabelSiswa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tabelSiswa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabelSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelSiswa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelSiswaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabelSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSiswaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelSiswa);
        if (tabelSiswa.getColumnModel().getColumnCount() > 0) {
            tabelSiswa.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tabelSiswa.getColumnModel().getColumn(1).setPreferredWidth(200);
            tabelSiswa.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tabelSiswa.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tabelSiswa.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("                INPUT DATA SISWA/SISWI SMK YAPPA DEPOK");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 30));

        tidsiswa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tidsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidsiswaActionPerformed(evt);
            }
        });
        jPanel1.add(tidsiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 239, 25));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NIS");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setFocusCycleRoot(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 48, 25));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA LENGKAP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 25));

        tnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaActionPerformed(evt);
            }
        });
        jPanel1.add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 239, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JENIS KELAMIN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 25));

        jk2.setBackground(new java.awt.Color(102, 102, 102));
        jk2.setForeground(new java.awt.Color(255, 255, 255));
        jk2.setText("P");
        jk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk2ActionPerformed(evt);
            }
        });
        jPanel1.add(jk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 25));

        jk1.setBackground(new java.awt.Color(102, 102, 102));
        jk1.setForeground(new java.awt.Color(255, 255, 255));
        jk1.setText("L");
        jk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk1ActionPerformed(evt);
            }
        });
        jPanel1.add(jk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 25));

        tkelas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cari Kelas" }));
        tkelas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkelasActionPerformed(evt);
            }
        });
        jPanel1.add(tkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 89, 25));

        tidkelas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tidkelas.setEnabled(false);
        tidkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidkelasActionPerformed(evt);
            }
        });
        jPanel1.add(tidkelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 43, 25));

        tombolSimpan.setBackground(new java.awt.Color(102, 102, 102));
        tombolSimpan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tombolSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tombolSimpan.setText("INPUT");
        tombolSimpan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(tombolSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 96, 25));

        tubah.setBackground(new java.awt.Color(102, 102, 102));
        tubah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tubah.setForeground(new java.awt.Color(255, 255, 255));
        tubah.setText("UBAH");
        tubah.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tubahActionPerformed(evt);
            }
        });
        jPanel1.add(tubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 96, 25));

        excel.setBackground(new java.awt.Color(102, 102, 102));
        excel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        excel.setForeground(new java.awt.Color(255, 255, 255));
        excel.setText("IMPORT EXCEL");
        excel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelActionPerformed(evt);
            }
        });
        jPanel1.add(excel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 96, 25));

        hapus.setBackground(new java.awt.Color(102, 102, 102));
        hapus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("HAPUS");
        hapus.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 96, 25));

        tabl1.setBackground(new java.awt.Color(102, 102, 102));
        tabl1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabl1.setForeground(new java.awt.Color(255, 255, 255));
        tabl1.setText("SIMPAN TABEL");
        tabl1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tabl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabl1ActionPerformed(evt);
            }
        });
        jPanel1.add(tabl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 96, 25));

        ctbl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ctbl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cari Data Kelas", "10.A", "10.B", "10.C", "10.D", "10.E", "11.A", "11.B", "11.C", "11.D", "11.E", "12.A", "12.B", "12.C", "12.D", "12.E" }));
        ctbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        ctbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctblActionPerformed(evt);
            }
        });
        jPanel1.add(ctbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 124, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tidkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidkelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidkelasActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        // TODO add your handling code here:
        String sql = "insert into t_siswa  values  (?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1, WIDTH);
            stat.setString(2, tidsiswa.getText());
            stat.setString(3, tnama.getText());
            
          
            String jkel="";
            if (jk1.isSelected()) jkel="L";
            else jkel = "P";
            stat.setString(4, jkel);
            stat.setString(5,tkelas.getSelectedItem().toString());
        
            stat.setString(6,tidkelas.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            tidsiswa.requestFocus();
            datatable();
            tbl();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaActionPerformed

    private void tabelSiswaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelSiswaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelSiswaAncestorAdded

    private void tabelSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSiswaMouseClicked
        // TODO add your handling code here:
        int bar = tabelSiswa.getSelectedRow();
        String a = tabmode.getValueAt(bar,0).toString();
        String b = tabmode.getValueAt(bar,1).toString();
        String c = tabmode.getValueAt(bar,2).toString();
        String d = tabmode.getValueAt(bar,3).toString();
        String e = tabmode.getValueAt(bar,4).toString();
       
        
       

        tidsiswa.setText(a);
        tnama.setText(b);
       
        

        if(c.equals("L")) {
            jk1.setSelected(true);
            jk2.setSelected(false);
        } else {
            jk1.setSelected(false);
            jk2.setSelected(true);
        }

        tkelas.setSelectedItem(d);
        
        tidkelas.setText(e);

    }//GEN-LAST:event_tabelSiswaMouseClicked

    private void tidsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidsiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidsiswaActionPerformed

    private void tkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkelasActionPerformed
        // TODO add your handling code here:
        String item = (String)tkelas.getSelectedItem();
        String sql= "select * From t_kelas where kelas = ? ";
        try{

            java.sql.Statement stat = conn.createStatement();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, item);
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                String id = rs.getString("id");
                tidkelas.setText(id);
            }

        }catch(Exception e){

        }
    }//GEN-LAST:event_tkelasActionPerformed

    private void jk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jk1ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0) {
            String sql = "delete from t_siswa where nama_siswa = '"+tnama.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
                kosong();
                tnama.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal Di Hapus"+e);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void jk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jk2ActionPerformed

    private void tubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tubahActionPerformed
        // TODO add your handling code here
        try {
             
            String sql = "update t_siswa set NIS=?, nama_siswa =?,jk=?,nama_kelas=?, id_kelas=? where NIS='"+tidsiswa.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);

            stat.setString(1,tidsiswa.getText());
            stat.setString(2,tnama.getText());
           
            
            String jkel="";
            if (jk1.isSelected()) jkel="L";
            else jkel = "P";
            stat.setString(3, jkel);
            stat.setString(4,tkelas.getSelectedItem().toString());
            
            stat.setString(5,tidkelas.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            tidsiswa.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
        
    }//GEN-LAST:event_tubahActionPerformed

    private void excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelActionPerformed
        // TODO add your handling code here:
        File excelFile;
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelImportToJTable = null;
        String defaultCurrentDirectoryPath = "";
        JFileChooser excelFileChooser = new JFileChooser(defaultCurrentDirectoryPath);
        excelFileChooser.setDialogTitle("Select Excel File");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showOpenDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                excelFile = excelFileChooser.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelImportToJTable = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelImportToJTable.getSheetAt(0);

                for (int row = 0; row < excelSheet.getLastRowNum(); row++) {
                    XSSFRow excelRow = excelSheet.getRow(row);

    
                    XSSFCell excelNIS = excelRow.getCell(0);
                    XSSFCell excelnama_siswa = excelRow.getCell(1);
                 
                    XSSFCell exceljk = excelRow.getCell(2);
                    XSSFCell excelnama_kelas = excelRow.getCell(3);
                    XSSFCell excelid_kelas = excelRow.getCell(4);
                    

                    tabmode.addRow(new Object[]{excelNIS, excelnama_siswa, exceljk, excelnama_kelas,excelid_kelas});
                }

                JOptionPane.showMessageDialog(null, "Imported Successfully !!.....");
            } catch (IOException iOException) {
                JOptionPane.showMessageDialog(null, iOException.getMessage());
            } finally {
                try {
                    if (excelFIS != null) {
                        excelFIS.close();
                    }
                    if (excelBIS != null) {
                        excelBIS.close();
                    }
                    if (excelImportToJTable != null) {
                        excelImportToJTable.close();
                    }
                } catch (IOException iOException) {
                    JOptionPane.showMessageDialog(null, iOException.getMessage());
                }
            }
        }
    }//GEN-LAST:event_excelActionPerformed

    private void tabl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabl1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabmode = (DefaultTableModel) tabelSiswa.getModel();
        if(tabmode.getRowCount()==0){

            JOptionPane.showMessageDialog(this,"Tabel tidak boleh kosong");

        }else{
            String  NIS,nama_siswa,jk,nama_kelas,id_kelas;
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/smk_yappa","root","");
                for(int i = 0;i<tabmode.getRowCount();i++){
                    NIS = tabmode.getValueAt(i,0).toString();
                    nama_siswa = tabmode.getValueAt(i,1).toString();
                    jk = tabmode.getValueAt(i,2).toString();
                    nama_kelas = tabmode.getValueAt(i,3).toString();
                    id_kelas = tabmode.getValueAt(i,4).toString();
                    

                    String query = "insert into t_siswa (NIS,nama_siswa,jk,nama_kelas,id_kelas) values(?,?,?,?,?)";
                    PreparedStatement prepstmt = con.prepareStatement(query);
                    prepstmt.setString(1,NIS);
                    prepstmt.setString(2,nama_siswa);
        
                    prepstmt.setString(3,jk);
                    prepstmt.setString(4,nama_kelas);
                    prepstmt.setString(5,id_kelas);
                   
                    prepstmt.execute();

                }

                JOptionPane.showMessageDialog(this, "Data berhasil dimasukan");

            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_tabl1ActionPerformed

    private void ctblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctblActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"NIS","NAMA SISWA","JENIS KELAMIN","KELAS","ID KELAS"};
        tabmode = new DefaultTableModel(null, Baris);
        tabelSiswa.setModel(tabmode);
        String sql = "select * from t_siswa where nama_kelas like '%"+ctbl.getSelectedItem()+"'";
        
        try {
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while (hasil.next()){
                    String a = hasil.getString("NIS");
                    String b = hasil.getString("nama_siswa");
                   
                    
                    String c = hasil.getString("jk");
                    String d = hasil.getString("nama_kelas");
                  
                    String e = hasil.getString("id_kelas");

                    String[] data={a,b,c,d,e};
                    tabmode.addRow(data);
                    tbl();
                }
            } catch (Exception e) {
        }
        
        /*String item = (String)ctbl.getSelectedItem();
        String sql= "select * From kelas where nama_kelas = '10.A'  ";
        try{

            java.sql.Statement stat = conn.createStatement();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, item);
            ResultSet rs = pst.executeQuery();
           
            if(rs.next()){
                
                tabelSiswa.setModel(tabmode);
            }

        }catch(Exception e){

        }
        */
    }//GEN-LAST:event_ctblActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ctbl;
    private javax.swing.JButton excel;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton jk1;
    private javax.swing.JRadioButton jk2;
    private javax.swing.JTable tabelSiswa;
    private javax.swing.JButton tabl1;
    private javax.swing.JTextField tidkelas;
    private javax.swing.JTextField tidsiswa;
    private javax.swing.JComboBox<String> tkelas;
    private javax.swing.JTextField tnama;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tubah;
    // End of variables declaration//GEN-END:variables
}
