    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author sahruli nur rizki
 */
public class FormPGuru extends javax.swing.JPanel {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;
    String Id_Guru = "";
    String Nip = "";
    String Nama_Guru = "";
    String No_Telpon = "";
    String Jenis_Kelamin = "";
    String Tanggal_Lahir ="";
    String Pendidikan="";
    String Alamat="";
    /**
     * Creates new form FormPGuru
     */
    public FormPGuru() {
        initComponents();
        datatable();
    }

    protected void aktif() {
        tguru.setEnabled(true);
      
        tnmguru.setEnabled(true);
        ttelp.setEnabled(true);
        
        talamat.setEnabled(true);
        tguru.requestFocus();
    }

    protected void kosong() {
        tguru.setText("");
       
        tnmguru.setText("");
        ttelp.setText("");
        jk1.setSelected(true);
       
        talamat.setText("");
        
        
           
    }
    protected void datatable () {
        Object[] Baris = {"ID GURU","NAMA GURU","ALAMAT","JENIS KELAMIN","NO TELPON"};
        tabmode = new DefaultTableModel(null, Baris);
        ttabelguru.setModel(tabmode);
        String sql = "select * from t_guru";
        try {
                java.sql.Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while (hasil.next()){
                    String a = hasil.getString("id_guru");
                    String b = hasil.getString("nama_guru");
                    String c = hasil.getString("alamat");
                    String d = hasil.getString("jk");
                    String e = hasil.getString("no_telp");
                    
                    
                    String[] data={a,b,c,d,e};
                    tabmode.addRow(data);
                }
            } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kd_guru = new javax.swing.JLabel();
        tguru = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tnmguru = new javax.swing.JTextField();
        ttelp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        talamat = new javax.swing.JTextArea();
        jk1 = new javax.swing.JRadioButton();
        jk2 = new javax.swing.JRadioButton();
        tombolSimpan = new javax.swing.JButton();
        bguru = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ttabelguru = new javax.swing.JTable();
        excel = new javax.swing.JButton();
        tabl = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(984, 547));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("               INPUT DATA GURU SMK YAPPA DEPOK");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -1, 360, 30));

        kd_guru.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        kd_guru.setForeground(new java.awt.Color(255, 255, 255));
        kd_guru.setText("ID GURU");
        jPanel4.add(kd_guru, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 25));

        tguru.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tguru.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tguruActionPerformed(evt);
            }
        });
        jPanel4.add(tguru, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 210, 25));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAMA LENGKAP");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 25));

        tnmguru.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tnmguru.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tnmguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnmguruActionPerformed(evt);
            }
        });
        jPanel4.add(tnmguru, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 210, 25));

        ttelp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ttelp.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        ttelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttelpActionPerformed(evt);
            }
        });
        jPanel4.add(ttelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 210, 25));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NO TELPON");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 25));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JENIS KELAMIN");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 25));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ALAMAT");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 25));

        talamat.setColumns(20);
        talamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        talamat.setRows(5);
        talamat.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(talamat);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 210, 106));

        jk1.setBackground(new java.awt.Color(102, 102, 102));
        jk1.setSelected(true);
        jk1.setText("L");
        jk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk1ActionPerformed(evt);
            }
        });
        jPanel4.add(jk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 30));

        jk2.setBackground(new java.awt.Color(102, 102, 102));
        jk2.setSelected(true);
        jk2.setText("P");
        jk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk2ActionPerformed(evt);
            }
        });
        jPanel4.add(jk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 30));

        tombolSimpan.setBackground(new java.awt.Color(102, 102, 102));
        tombolSimpan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tombolSimpan.setForeground(new java.awt.Color(255, 255, 255));
        tombolSimpan.setText("INPUT");
        tombolSimpan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(tombolSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 25));

        bguru.setBackground(new java.awt.Color(102, 102, 102));
        bguru.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bguru.setForeground(new java.awt.Color(255, 255, 255));
        bguru.setText("UBAH");
        bguru.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguruActionPerformed(evt);
            }
        });
        jPanel4.add(bguru, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 100, 25));

        hapus.setBackground(new java.awt.Color(102, 102, 102));
        hapus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("HAPUS");
        hapus.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel4.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 100, 25));

        ttabelguru.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        ttabelguru.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ttabelguru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        ttabelguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ttabelguruMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ttabelguru);

        excel.setBackground(new java.awt.Color(102, 102, 102));
        excel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        excel.setForeground(new java.awt.Color(255, 255, 255));
        excel.setText("IMPORT EXCEL");
        excel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelActionPerformed(evt);
            }
        });

        tabl.setBackground(new java.awt.Color(102, 102, 102));
        tabl.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tabl.setForeground(new java.awt.Color(255, 255, 255));
        tabl.setText("SIMPAN TABEL");
        tabl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        tabl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(tabl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ttabelguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ttabelguruMouseClicked
        // TODO add your handling code here:
        int bar = ttabelguru.getSelectedRow();
        String a = tabmode.getValueAt(bar,0).toString();
        String b = tabmode.getValueAt(bar,1).toString();
        String c = tabmode.getValueAt(bar,2).toString();
        String d = tabmode.getValueAt(bar,3).toString();
        String e = tabmode.getValueAt(bar,4).toString();
       

        tguru.setText(a);
        
        tnmguru.setText(b);
        ttelp.setText(c);
        if(d.equals("L")) {
            jk1.setSelected(true);
            jk2.setSelected(false);
        } else {
            jk1.setSelected(false);
            jk2.setSelected(true);
        }       
        talamat.setText(e);
    }//GEN-LAST:event_ttabelguruMouseClicked

    private void tablActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabmode = (DefaultTableModel) ttabelguru.getModel();
        if(tabmode.getRowCount()==0){

            JOptionPane.showMessageDialog(this,"Tabel tidak boleh kosong");

        }else{
            String  Id_Guru,Nip,Nama_Guru,No_Telpon,Jenis_Kelamin,Tanggal_Lahir,Pendidikan,Alamat;
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistem_akademik4","root","");
                for(int i = 0;i<tabmode.getRowCount();i++){
                    Id_Guru = tabmode.getValueAt(i,0).toString();
                    Nip = tabmode.getValueAt(i,1).toString();
                    Nama_Guru = tabmode.getValueAt(i,2).toString();
                    No_Telpon = tabmode.getValueAt(i,3).toString();
                    Jenis_Kelamin = tabmode.getValueAt(i,4).toString();
                    Tanggal_Lahir = tabmode.getValueAt(i,5).toString();
                    Pendidikan = tabmode.getValueAt(i,6).toString();
                    Alamat = tabmode.getValueAt(i,7).toString();

                    String query = "insert into mapel (id_guru,nip_guru,nama_guru,no_telp,jenis_kelamin,tgl_lahir,pendidikan_terakhir,alamat) values(?,?,?,?,?,?,?,?)";
                    PreparedStatement prepstmt = con.prepareStatement(query);
                    prepstmt.setString(1,Id_Guru);
                    prepstmt.setString(2,Nip);
                    prepstmt.setString(3,Nama_Guru);
                    prepstmt.setString(4,No_Telpon);
                    prepstmt.setString(5,Jenis_Kelamin);
                    prepstmt.setString(6,Tanggal_Lahir);
                    prepstmt.setString(7,Pendidikan);
                    prepstmt.setString(8,Alamat);
                    prepstmt.execute();

                }

                JOptionPane.showMessageDialog(this, "Data berhasil dimasukan");

            }catch(Exception e){

            }
        }
    }//GEN-LAST:event_tablActionPerformed

    private void excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelActionPerformed
        // TODO add your handling code here:
        File excelFile;
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelImportToJTable = null;
        String defaultCurrentDirectoryPath = "";
        JFileChooser excelFileChooser = new JFileChooser(defaultCurrentDirectoryPath);
        excelFileChooser.setDialogTitle("Select Excel File");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showOpenDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            try {
                excelFile = excelFileChooser.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                excelImportToJTable = new XSSFWorkbook(excelBIS);
                XSSFSheet excelSheet = excelImportToJTable.getSheetAt(0);

                for (int row = 0; row < excelSheet.getLastRowNum(); row++) {
                    XSSFRow excelRow = excelSheet.getRow(row);

                    XSSFCell excelId_Guru = excelRow.getCell(0);
                    XSSFCell excelNip = excelRow.getCell(1);
                    XSSFCell excelNama_Guru = excelRow.getCell(2);
                    XSSFCell excelNo_Telpon = excelRow.getCell(3);
                    XSSFCell excelJenis_Kelamin = excelRow.getCell(4);
                    XSSFCell excelTanggal_Lahir = excelRow.getCell(5);
                    XSSFCell excelPendidikan = excelRow.getCell(6);
                    XSSFCell excelAlamat = excelRow.getCell(7);

                    tabmode.addRow(new Object[]{excelId_Guru, excelNip, excelNama_Guru, excelNo_Telpon, excelJenis_Kelamin,excelTanggal_Lahir, excelPendidikan, excelAlamat });
                }

                JOptionPane.showMessageDialog(null, "Imported Successfully !!.....");
            } catch (IOException iOException) {
                JOptionPane.showMessageDialog(null, iOException.getMessage());
            } finally {
                try {
                    if (excelFIS != null) {
                        excelFIS.close();
                    }
                    if (excelBIS != null) {
                        excelBIS.close();
                    }
                    if (excelImportToJTable != null) {
                        excelImportToJTable.close();
                    }
                } catch (IOException iOException) {
                    JOptionPane.showMessageDialog(null, iOException.getMessage());
                }
            }
        }
    }//GEN-LAST:event_excelActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "Hapus","Konfirmasi Dialog",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0) {
            String sql = "delete from t_guru where nama_guru = '"+tnmguru.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
                kosong();
                tnmguru.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal Di Hapus"+e);
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void bguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguruActionPerformed
        // TODO add your handling code here:
        try {

            String sql = "update t_guru set id_guru=?,nama_guru=?, no_telp=?,jk=?,alamat=? where id_guru='"+tguru.getText()+"'";

            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,tguru.getText());
            
            stat.setString(2,tnmguru.getText());
            stat.setString(3,ttelp.getText());
            String jkel="";
            if (jk1.isSelected()) jkel="L";
            else jkel = "P";
            stat.setString(4, jkel);
          
            stat.setString(5,talamat.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            tguru.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_bguruActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        // TODO add your handling code here:
        String sql = "insert into t_guru values (?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,tguru.getText());
           
            stat.setString(2,tnmguru.getText());
            stat.setString(3,ttelp.getText());
            String jkel="";
            if (jk1.isSelected()) jkel="L";
            else jkel = "P";
            stat.setString(4, jkel);
            stat.setString(5,talamat.getText());

            //Checking if one or more field is empty

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            tguru.requestFocus();
            datatable();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void jk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jk2ActionPerformed

    private void jk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jk1ActionPerformed

    private void ttelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttelpActionPerformed

    private void tnmguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnmguruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnmguruActionPerformed

    private void tguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tguruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tguruActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bguru;
    private javax.swing.JButton excel;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jk1;
    private javax.swing.JRadioButton jk2;
    private javax.swing.JLabel kd_guru;
    private javax.swing.JButton tabl;
    private javax.swing.JTextArea talamat;
    private javax.swing.JTextField tguru;
    private javax.swing.JTextField tnmguru;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JTable ttabelguru;
    private javax.swing.JTextField ttelp;
    // End of variables declaration//GEN-END:variables
}
